### ISSUE TITLE
Maximize does not work as expected.

### ISSUE THREAD

**Issue by pitgrap** [userlike/messenger#10]
Hi, I'm new to userlike and need to build a full page chat app for a customer.
I build a React App similiar to the playground but have some problems:

The chat does not maximize deterministic. Sometime it opens, sometimes not. Even if I delete all cookies and localstorage.
All I do is loading the api via `useAsync` and `React.useMemo` and then running `api.mount().then(api.maximize());` in the app.
What can I do to get the app maximized everytime?

Is it also possible to change the size etc. of the messenger. I would like run it on the whole screen, not just in a small overlay frame.

**Comment by anilanar** [comment]
> Is it also possible to change the size etc. of the messenger. I would like run it on the whole screen, not just in a small overlay frame.

That's a feature request for the Userlike product. For feature requests, please contact Userlike via other channels.

> The chat does not maximize deterministic. Sometime it opens, sometimes not. Even if I delete all cookies and localstorage.
All I do is loading the api via useAsync and React.useMemo and then running api.mount().then(api.maximize()); in the app.
What can I do to get the app maximized everytime?

Can you try the following? You can only maximize if messenger state is `minimized` (i.e. when it's not `hidden` and not `maximized`).

```
  React.useEffect(() => {
    api.state$.subscribe({
      next({ state }) {
        if (state === "minimized") {
          api.maximize();
        }
      }
    });
  });
```

**Comment by pitgrap** [comment]
Thank you. That works, but I always have to wrap it in `if(api !== undefined) { ... }` otherwise webpack cannot build it.

Now, that the chat is always maximized, can I hide/remove the minimize button? I couldn't find an option in `VisibilityConfiguration`.

**Comment by anilanar** [comment]
@pitgrap Sorry, there's no such capability.

**Comment by pitgrap** [comment]
Ok, never mind.

> For feature requests, please contact Userlike via other channels.

Could you give me a hint, where to find the "other channels". I would like to get rid off the rounded corners... ;)

**Comment by anilanar** [comment]
@pitgrap https://www.userlike.com/en/support

**Comment by pitgrap** [comment]
Thank you!

**Comment by vblanches** [comment]
Hi, sorry to dig this closed ticket up, but I'm actually trying to achieve the same as the original author (get the app maximized everytime the page loads) and I'm having hard time to do it. I'm no React developper and my only experience with Userlike was the previous "Live Chat".

I'm using the Skypack CDN to import Userlike and React, but I get an "Uncaught Error: Minified React error #321" error in the console when using the code you provided in [this comment](https://github.com/userlike/messenger/issues/10#issuecomment-744408069).

Here is the code Example: https://codepen.io/vblanches/pen/OJWxKMz

Do you have any idea how I could fix this?

**Comment by anilanar** [comment]
@vblanches Hi, you were pretty close but the React bits confused you it seems. The api has nothing to do with React actually, it was just that the tutorial was using React as an example.

This code snippet should work:

```javascript
import { createMessenger } from 'https://cdn.skypack.dev/@userlike/messenger@1.1.1';

async function createApi() {
  const result = await createMessenger({
    version: 1,
    widgetKey: '7309183f69e24dd580fb4926951a948740f1ba9e443243e0bef25ea0fd4f87b8',
  });

  if (result.kind === 'error') {
    throw new Error(result.error);
  }

  const { api } = result.value;

  if (api === null) {
    throw new Error('api reached end-of-life, please check documentation and upgrade.');
  }

  return api;
}

async function run() {
  const api = await createApi();

  await api.mount();

  await api.setVisibility({
    main: true,
    button: false,
    notifications: false,
  });

  const { unsubscribe } = api.state$.subscribe({
    next({ state }) {
      if (state === 'minimized') {
        api.maximize();
        // if you want to maximize only once
        // otherwise this will block minimize completely
        // unsubscribe();
      }
    },
  });

  document.getElementById('myBtn').addEventListener('click', () => api.maximize());
}

run().catch(error => {
  console.error(error);
});
```

**Comment by vblanches** [comment]
Amazing, works like a charm! ;)

Thanks for your quick support @anilanar :)

**Comment by mgrubinger** [comment]
FTR: I just had the exact same issue. You might want to add this to the docs.
