### ISSUE TITLE
Add build output for browsers

### ISSUE THREAD

**Issue by anilanar** [userlike/messenger#14]
Currently, the messenger requires using a bundler (like webpack/snowpack/browserify) or a CDN with bundling capability such as skypack.dev. 

Let's introduce a way for customers to use traditional methods to use the messenger api.

**Comment by BoBaH83** [comment]
@anilanar any update on this? also I think this should be a must have. not an enhancement.

**Comment by anilanar** [comment]
@BoBaH83 This is now fixed.

If you are using npm, the file is in `node_modules/@userlike/messenger/dist/browser/index.min.js`. 

Otherwise, it can also be accessed using [unpkg](https://unpkg.com/@userlike/messenger/dist/browser/index.min.js).
