### ISSUE TITLE
Error handling for createMessenger

### ISSUE THREAD

**Issue by mgrubinger** [userlike/messenger#20]
I can't seem to find a way to react to loading failures when calling `createMessenger()`

Here's my `createApi` function (based on the examples/docs):

```
async function createApi() {
  let result;
  try {
    result = await createMessenger({
      version: 1,
      widgetKey: "BOGUS",
    });
  } catch (error) {
      console.log(error)
  }

  if (result.kind === "error") throw new Error(result.error);
  const { api } = result.value;
  return api;
};
```

Notice, how the **widgetKey** is set to a random string?
However, neither result.kind === 'error' nor will createMessenger it throw an error that I could catch. It just fails silently.

The same applies, when the resources can not be loaded (umm-runtime...js etc).

I would like to check for errors when initializing the component to reflect that in the UI.

Thanks

**Comment by buscape** [comment]
Hey @mgrubinger 

Can you try something like
```
 const result = await createMessenger({
    version: 1,
    widgetKey: "YOUR_WIDGET_SECRET",
  });

  if (result.kind === "error") throw new Error(result.error);
```
and report if that archieves your desired behaviour?

Messenger API won't throw an error to be polite and not interfere with your other code or pollute the console. 
So you need to throw the error yourself (eg. there is nothing you can `catch` in your try/catch block).

**Comment by mgrubinger** [comment]
Thanks for your response.
However, `result.kind` is still `success` – even if the widgetKey is just some random string.

When I then `.mount()` the widget, I still can't catch an error, but you can see in the network tab that it is trying to request a file named `YOUR_WIDGET_KEY.json` (or whatever I put in `widgetKey`). But no error I could react to.

If the resources can not be loaded, apparently createMessenger silently returns.

I've set up a simple reproduction of the issues I'm talking about:
https://stackblitz.com/edit/js-zopxan?devtoolsheight=33&file=index.js

**Comment by buscape** [comment]
@mgrubinger you’re right, it’s a limitation of our API that you’re not guaranteed to get errors in all cases.
However, you should get an error result when you try to call the mount function of Messenger API with an invalid widgetKey.
Given this code snippet:

```ts
import { createMessenger } from '@userlike/messenger';

async function mountUserlike() {
  console.log('start mounting');

  const result = await createMessenger({
    version: 1,
    widgetKey: 'BOGUS',
  });

  // 1) result.kind is 'success' even though we provided a wrong key
  // 2) if the JS resources can't be loaded (blocked via network tab for testing purposes) we're not even reaching this point
  console.log(result);
  if (result.kind === 'error') throw new Error(result.error);

  // `api` seems fine, but can't mount because of wrong widgetKey
  let { api } = result.value;
  console.log(api);

  // mount() will try to request this file: `https://userlike-cdn-widgets.s3-eu-west-1.amazonaws.com/BOGUS.json`
  const mountResult = await api.mount();
  console.log(mountResult);
  if (mountResult.kind === 'error') throw new Error(mountResult.error);
}

// attach event listener
const button = document.getElementById('load-userlike-button');
button.addEventListener('click', async () => {
  try {
    await mountUserlike();
  } catch (e) {
    console.log('Error mounting userlike', e.message);
  }
});
```

you’ll receive an error when calling `mount()` with and invalid widget key or when fe blocking the request to `umm-manifest.json`

**Comment by mgrubinger** [comment]
Hi @buscape – thanks, yes – the return value of `api.mount()` is `kind: 'error'`, perfect. 
Since the umm-manifest.json is the first thing to load, it's probably good enough to check for an error based on that. 

Thanks for your help! 👏
